// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct connection, not the pooled one the app uses
    // at runtime (lib/db.ts) — DATABASE_URL_UNPOOLED is only set on Vercel;
    // local dev falls back to DATABASE_URL (a plain, unpooled local Postgres).
    url: process.env["DATABASE_URL_UNPOOLED"] || process.env["DATABASE_URL"],
  },
});
